name: UBARecode
version: '${project.version}'
main: com.somemone.ubarecode.UnitedBaseAlert
api-version: 1.18

commands:
  basealert:
    usage: /ba <generate|info>
    aliases: [ba, balert]
  baseadmin:
    usage: /baseadmin <renew|create>
    description: BaseAlert Command for console/mod use
    aliases: [badmin]
    permission: basealert.admin

permissions:
  basealert.admin:
    default: op